# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/base64/all/base64.rbi
#
# base64-0.3.0

module Base64
  def decode64(str); end
  def encode64(bin); end
  def self.decode64(str); end
  def self.encode64(bin); end
  def self.strict_decode64(str); end
  def self.strict_encode64(bin); end
  def self.urlsafe_decode64(str); end
  def self.urlsafe_encode64(bin, padding: nil); end
  def strict_decode64(str); end
  def strict_encode64(bin); end
  def urlsafe_decode64(str); end
  def urlsafe_encode64(bin, padding: nil); end
end
