# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/chunky_png/all/chunky_png.rbi
#
# chunky_png-1.4.0

module ChunkyPNG
end
class ChunkyPNG::Datastream
end
module ChunkyPNG::Chunk
end
class ChunkyPNG::Chunk::Base
end
class ChunkyPNG::Chunk::Generic < ChunkyPNG::Chunk::Base
end
class ChunkyPNG::Chunk::Header < ChunkyPNG::Chunk::Base
end
class ChunkyPNG::Chunk::End < ChunkyPNG::Chunk::Base
end
class ChunkyPNG::Chunk::Palette < ChunkyPNG::Chunk::Generic
end
class ChunkyPNG::Chunk::Transparency < ChunkyPNG::Chunk::Generic
end
class ChunkyPNG::Chunk::ImageData < ChunkyPNG::Chunk::Generic
end
class ChunkyPNG::Chunk::Text < ChunkyPNG::Chunk::Base
end
class ChunkyPNG::Chunk::CompressedText < ChunkyPNG::Chunk::Base
end
class ChunkyPNG::Chunk::Physical < ChunkyPNG::Chunk::Base
end
class ChunkyPNG::Chunk::InternationalText < ChunkyPNG::Chunk::Base
end
class ChunkyPNG::Palette < Set
end
module ChunkyPNG::Color
  extend ChunkyPNG::Color
end
class ChunkyPNG::Point
end
class ChunkyPNG::Vector
  include Enumerable
end
class ChunkyPNG::Dimension
end
class ChunkyPNG::Canvas
  extend ChunkyPNG::Canvas::Adam7Interlacing
  extend ChunkyPNG::Canvas::DataUrlImporting
  extend ChunkyPNG::Canvas::PNGDecoding
  extend ChunkyPNG::Canvas::StreamImporting
  include ChunkyPNG::Canvas::DataUrlExporting
  include ChunkyPNG::Canvas::Drawing
  include ChunkyPNG::Canvas::Masking
  include ChunkyPNG::Canvas::Operations
  include ChunkyPNG::Canvas::PNGEncoding
  include ChunkyPNG::Canvas::Resampling
  include ChunkyPNG::Canvas::StreamExporting
end
module ChunkyPNG::Canvas::PNGEncoding
end
module ChunkyPNG::Canvas::PNGDecoding
end
module ChunkyPNG::Canvas::Adam7Interlacing
end
module ChunkyPNG::Canvas::StreamExporting
end
module ChunkyPNG::Canvas::StreamImporting
end
module ChunkyPNG::Canvas::DataUrlExporting
end
module ChunkyPNG::Canvas::DataUrlImporting
end
module ChunkyPNG::Canvas::Operations
end
module ChunkyPNG::Canvas::Drawing
end
module ChunkyPNG::Canvas::Resampling
end
module ChunkyPNG::Canvas::Masking
end
class ChunkyPNG::Image < ChunkyPNG::Canvas
end
class ChunkyPNG::Exception < StandardError
end
class ChunkyPNG::NotSupported < ChunkyPNG::Exception
end
class ChunkyPNG::SignatureMismatch < ChunkyPNG::Exception
end
class ChunkyPNG::CRCMismatch < ChunkyPNG::Exception
end
class ChunkyPNG::InvalidUTF8 < ChunkyPNG::Exception
end
class ChunkyPNG::ExpectationFailed < ChunkyPNG::Exception
end
class ChunkyPNG::OutOfBounds < ChunkyPNG::ExpectationFailed
end
class ChunkyPNG::UnitsUnknown < ChunkyPNG::Exception
end
