# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/connection_pool/all/connection_pool.rbi
#
# connection_pool-2.5.3

class ConnectionPool
end
class ConnectionPool::TimedStack
end
class ConnectionPool::Wrapper < BasicObject
end
class ConnectionPool::Error < RuntimeError
end
class ConnectionPool::PoolShuttingDownError < ConnectionPool::Error
end
class ConnectionPool::TimeoutError < Timeout::Error
end
module ConnectionPool::ForkTracker
end
