# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/diff-lcs/all/diff-lcs.rbi
#
# diff-lcs-1.6.2

module Diff
end
module Diff::LCS
end
class Diff::LCS::Change
  include Comparable
end
class Diff::LCS::ContextChange < Diff::LCS::Change
end
class Diff::LCS::DefaultCallbacks
end
class Diff::LCS::DiffCallbacks
end
class Diff::LCS::ContextDiffCallbacks < Diff::LCS::DiffCallbacks
end
class Diff::LCS::SDiffCallbacks
end
module Diff::LCS::Internals
end
class Diff::LCS::Block
end
class Diff::LCS::Hunk
end
