# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/erb-formatter/all/erb-formatter.rbi
#
# erb-formatter-0.7.3

class ERB::Formatter
end
module ERB::Formatter::SyntaxTreeCommandPatch
end
class ERB::Formatter::Error < StandardError
end
module ERB::Formatter::DebugShovel
end
