# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/erubi/all/erubi.rbi
#
# erubi-1.13.1

module Erubi
end
class Erubi::Engine
end
