# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday-net_http/all/faraday-net_http.rbi
#
# faraday-net_http-3.4.1

module Faraday
end
class Faraday::Adapter
end
class Faraday::Adapter::NetHttp < Faraday::Adapter
end
module Faraday::NetHttp
end
