# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday/all/faraday.rbi
#
# faraday-2.13.2

module Faraday
end
class Faraday::Error < StandardError
end
class Faraday::ClientError < Faraday::Error
end
class Faraday::BadRequestError < Faraday::ClientError
end
class Faraday::UnauthorizedError < Faraday::ClientError
end
class Faraday::ForbiddenError < Faraday::ClientError
end
class Faraday::ResourceNotFound < Faraday::ClientError
end
class Faraday::ProxyAuthError < Faraday::ClientError
end
class Faraday::RequestTimeoutError < Faraday::ClientError
end
class Faraday::ConflictError < Faraday::ClientError
end
class Faraday::UnprocessableEntityError < Faraday::ClientError
end
class Faraday::TooManyRequestsError < Faraday::ClientError
end
class Faraday::ServerError < Faraday::Error
end
class Faraday::TimeoutError < Faraday::ServerError
end
class Faraday::NilStatusError < Faraday::ServerError
end
class Faraday::ConnectionFailed < Faraday::Error
end
class Faraday::SSLError < Faraday::Error
end
class Faraday::ParsingError < Faraday::Error
end
class Faraday::InitializationError < Faraday::Error
end
module Faraday::MiddlewareRegistry
end
module Faraday::Utils
end
class Faraday::Utils::Headers < Hash
end
class Faraday::Utils::ParamsHash < Hash
end
class Faraday::ProxyOptions < Faraday::Options
  extend Forwardable
end
class Faraday::Env < Faraday::Options
  extend Forwardable
end
class Faraday::Options < Struct
end
class Faraday::Connection
  extend Forwardable
end
class Faraday::AdapterRegistry
end
class Faraday::RackBuilder
end
class Faraday::RackBuilder::StackLocked < RuntimeError
end
class Faraday::RackBuilder::Handler
end
module Faraday::EncodeMethods
end
module Faraday::DecodeMethods
end
module Faraday::NestedParamsEncoder
  extend Faraday::DecodeMethods
  extend Faraday::EncodeMethods
end
module Faraday::FlatParamsEncoder
end
class Faraday::Middleware
  extend Faraday::MiddlewareRegistry
end
class Faraday::Adapter
  extend Faraday::Adapter::Parallelism
  extend Faraday::MiddlewareRegistry
end
class Faraday::Adapter::Test < Faraday::Adapter
end
class Faraday::Adapter::Test::Stubs
end
class Faraday::Adapter::Test::Stubs::NotFound < StandardError
end
module Faraday::Adapter::Parallelism
end
class Faraday::Request < Struct
  extend Faraday::MiddlewareRegistry
end
class Faraday::Request::Authorization < Faraday::Middleware
end
class Faraday::Request::Instrumentation < Faraday::Middleware
end
class Faraday::Request::Json < Faraday::Middleware
end
class Faraday::Request::UrlEncoded < Faraday::Middleware
end
class Faraday::Response
  extend Faraday::MiddlewareRegistry
  extend Forwardable
end
class Faraday::Response::Json < Faraday::Middleware
end
module Faraday::Logging
end
class Faraday::Logging::Formatter
  extend Forwardable
end
class Faraday::Response::Logger < Faraday::Middleware
end
class Faraday::Response::RaiseError < Faraday::Middleware
end
