# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jwt/all/jwt.rbi
#
# jwt-3.1.2

module JWT
  extend JWT::Configuration
end
module JWT::VERSION
end
class JWT::Base64
end
class JWT::JSON
end
class JWT::X5cKeyFinder
end
class JWT::Decode
end
module JWT::Configuration
end
class JWT::Configuration::DecodeConfiguration
end
module JWT::JWK
end
class JWT::JWK::KidAsKeyDigest
end
class JWT::JWK::Thumbprint
end
class JWT::Configuration::JwkConfiguration
end
class JWT::Configuration::Container
end
module JWT::JWA
end
module JWT::JWA::SigningAlgorithm
end
module JWT::JWA::SigningAlgorithm::ClassMethods
end
class JWT::JWA::Ecdsa
  extend JWT::JWA::SigningAlgorithm::ClassMethods
  include JWT::JWA::SigningAlgorithm
end
class JWT::JWA::Hmac
  extend JWT::JWA::SigningAlgorithm::ClassMethods
  include JWT::JWA::SigningAlgorithm
end
module JWT::JWA::Hmac::SecurityUtils
end
class JWT::JWA::None
  extend JWT::JWA::SigningAlgorithm::ClassMethods
  include JWT::JWA::SigningAlgorithm
end
class JWT::JWA::Ps
  extend JWT::JWA::SigningAlgorithm::ClassMethods
  include JWT::JWA::SigningAlgorithm
end
class JWT::JWA::Rsa
  extend JWT::JWA::SigningAlgorithm::ClassMethods
  include JWT::JWA::SigningAlgorithm
end
module JWT::JWA::Unsupported
end
class JWT::JWA::VerifierContext
end
class JWT::JWA::SignerContext
end
class JWT::Encode
end
class JWT::EncodeError < StandardError
end
class JWT::DecodeError < StandardError
end
class JWT::VerificationError < JWT::DecodeError
end
class JWT::ExpiredSignature < JWT::DecodeError
end
class JWT::IncorrectAlgorithm < JWT::DecodeError
end
class JWT::ImmatureSignature < JWT::DecodeError
end
class JWT::InvalidIssuerError < JWT::DecodeError
end
class JWT::UnsupportedEcdsaCurve < JWT::IncorrectAlgorithm
end
class JWT::InvalidIatError < JWT::DecodeError
end
class JWT::InvalidAudError < JWT::DecodeError
end
class JWT::InvalidSubError < JWT::DecodeError
end
class JWT::InvalidCritError < JWT::DecodeError
end
class JWT::InvalidJtiError < JWT::DecodeError
end
class JWT::InvalidPayload < JWT::DecodeError
end
class JWT::MissingRequiredClaim < JWT::DecodeError
end
class JWT::Base64DecodeError < JWT::DecodeError
end
class JWT::JWKError < JWT::DecodeError
end
class JWT::JWK::KeyFinder
end
class JWT::JWK::Set
  extend Forwardable
  include Enumerable
end
class JWT::JWK::KeyBase
end
class JWT::JWK::EC < JWT::JWK::KeyBase
end
class JWT::JWK::RSA < JWT::JWK::KeyBase
end
class JWT::JWK::HMAC < JWT::JWK::KeyBase
end
module JWT::Claims
end
class JWT::Claims::Audience
end
class JWT::Claims::Crit
end
module JWT::Claims::DecodeVerifier
end
class JWT::Claims::Expiration
end
class JWT::Claims::IssuedAt
end
class JWT::Claims::Issuer
end
class JWT::Claims::JwtId
end
class JWT::Claims::NotBefore
end
class JWT::Claims::Numeric
end
class JWT::Claims::Required
end
class JWT::Claims::Subject
end
module JWT::Claims::Verifier
end
class JWT::EncodedToken
end
class JWT::EncodedToken::ClaimsContext
  extend Forwardable
end
class JWT::Token
end
