# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/multi_xml/all/multi_xml.rbi
#
# multi_xml-0.7.2

module MultiXml
end
class MultiXml::ParseError < StandardError
end
class MultiXml::NoParserError < StandardError
end
class MultiXml::DisallowedTypeError < StandardError
end
module InvalidName___Class_0x00___FileLike_59
end
