# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/net-http/all/net-http.rbi
#
# net-http-0.6.0

module Net
end
module Net::HTTPExceptions
end
class Net::HTTPError < Net::ProtocolError
  include Net::HTTPExceptions
end
class Net::HTTPRetriableError < Net::ProtoRetriableError
  include Net::HTTPExceptions
end
class Net::HTTPClientException < Net::ProtoServerError
  include Net::HTTPExceptions
end
class Net::HTTPFatalError < Net::ProtoFatalError
  include Net::HTTPExceptions
end
module Net::HTTPHeader
end
class Net::HTTPGenericRequest
  include Net::HTTPHeader
end
class Net::HTTPGenericRequest::Chunker
end
class Net::HTTPRequest < Net::HTTPGenericRequest
end
class Net::HTTP::Get < Net::HTTPRequest
end
class Net::HTTP::Head < Net::HTTPRequest
end
class Net::HTTP::Post < Net::HTTPRequest
end
class Net::HTTP::Put < Net::HTTPRequest
end
class Net::HTTP::Delete < Net::HTTPRequest
end
class Net::HTTP::Options < Net::HTTPRequest
end
class Net::HTTP::Trace < Net::HTTPRequest
end
class Net::HTTP::Patch < Net::HTTPRequest
end
class Net::HTTP::Propfind < Net::HTTPRequest
end
class Net::HTTP::Proppatch < Net::HTTPRequest
end
class Net::HTTP::Mkcol < Net::HTTPRequest
end
class Net::HTTP::Copy < Net::HTTPRequest
end
class Net::HTTP::Move < Net::HTTPRequest
end
class Net::HTTP::Lock < Net::HTTPRequest
end
class Net::HTTP::Unlock < Net::HTTPRequest
end
class Net::HTTPResponse
  include Net::HTTPHeader
end
class Net::HTTPResponse::Inflater
end
class Net::HTTPUnknownResponse < Net::HTTPResponse
end
class Net::HTTPInformation < Net::HTTPResponse
end
class Net::HTTPSuccess < Net::HTTPResponse
end
class Net::HTTPRedirection < Net::HTTPResponse
end
class Net::HTTPClientError < Net::HTTPResponse
end
class Net::HTTPServerError < Net::HTTPResponse
end
class Net::HTTPContinue < Net::HTTPInformation
end
class Net::HTTPSwitchProtocol < Net::HTTPInformation
end
class Net::HTTPProcessing < Net::HTTPInformation
end
class Net::HTTPEarlyHints < Net::HTTPInformation
end
class Net::HTTPOK < Net::HTTPSuccess
end
class Net::HTTPCreated < Net::HTTPSuccess
end
class Net::HTTPAccepted < Net::HTTPSuccess
end
class Net::HTTPNonAuthoritativeInformation < Net::HTTPSuccess
end
class Net::HTTPNoContent < Net::HTTPSuccess
end
class Net::HTTPResetContent < Net::HTTPSuccess
end
class Net::HTTPPartialContent < Net::HTTPSuccess
end
class Net::HTTPMultiStatus < Net::HTTPSuccess
end
class Net::HTTPAlreadyReported < Net::HTTPSuccess
end
class Net::HTTPIMUsed < Net::HTTPSuccess
end
class Net::HTTPMultipleChoices < Net::HTTPRedirection
end
class Net::HTTPMovedPermanently < Net::HTTPRedirection
end
class Net::HTTPFound < Net::HTTPRedirection
end
class Net::HTTPSeeOther < Net::HTTPRedirection
end
class Net::HTTPNotModified < Net::HTTPRedirection
end
class Net::HTTPUseProxy < Net::HTTPRedirection
end
class Net::HTTPTemporaryRedirect < Net::HTTPRedirection
end
class Net::HTTPPermanentRedirect < Net::HTTPRedirection
end
class Net::HTTPBadRequest < Net::HTTPClientError
end
class Net::HTTPUnauthorized < Net::HTTPClientError
end
class Net::HTTPPaymentRequired < Net::HTTPClientError
end
class Net::HTTPForbidden < Net::HTTPClientError
end
class Net::HTTPNotFound < Net::HTTPClientError
end
class Net::HTTPMethodNotAllowed < Net::HTTPClientError
end
class Net::HTTPNotAcceptable < Net::HTTPClientError
end
class Net::HTTPProxyAuthenticationRequired < Net::HTTPClientError
end
class Net::HTTPRequestTimeout < Net::HTTPClientError
end
class Net::HTTPConflict < Net::HTTPClientError
end
class Net::HTTPGone < Net::HTTPClientError
end
class Net::HTTPLengthRequired < Net::HTTPClientError
end
class Net::HTTPPreconditionFailed < Net::HTTPClientError
end
class Net::HTTPPayloadTooLarge < Net::HTTPClientError
end
class Net::HTTPURITooLong < Net::HTTPClientError
end
class Net::HTTPUnsupportedMediaType < Net::HTTPClientError
end
class Net::HTTPRangeNotSatisfiable < Net::HTTPClientError
end
class Net::HTTPExpectationFailed < Net::HTTPClientError
end
class Net::HTTPMisdirectedRequest < Net::HTTPClientError
end
class Net::HTTPUnprocessableEntity < Net::HTTPClientError
end
class Net::HTTPLocked < Net::HTTPClientError
end
class Net::HTTPFailedDependency < Net::HTTPClientError
end
class Net::HTTPUpgradeRequired < Net::HTTPClientError
end
class Net::HTTPPreconditionRequired < Net::HTTPClientError
end
class Net::HTTPTooManyRequests < Net::HTTPClientError
end
class Net::HTTPRequestHeaderFieldsTooLarge < Net::HTTPClientError
end
class Net::HTTPUnavailableForLegalReasons < Net::HTTPClientError
end
class Net::HTTPInternalServerError < Net::HTTPServerError
end
class Net::HTTPNotImplemented < Net::HTTPServerError
end
class Net::HTTPBadGateway < Net::HTTPServerError
end
class Net::HTTPServiceUnavailable < Net::HTTPServerError
end
class Net::HTTPGatewayTimeout < Net::HTTPServerError
end
class Net::HTTPVersionNotSupported < Net::HTTPServerError
end
class Net::HTTPVariantAlsoNegotiates < Net::HTTPServerError
end
class Net::HTTPInsufficientStorage < Net::HTTPServerError
end
class Net::HTTPLoopDetected < Net::HTTPServerError
end
class Net::HTTPNotExtended < Net::HTTPServerError
end
class Net::HTTPNetworkAuthenticationRequired < Net::HTTPServerError
end
module Net::HTTP::ProxyDelta
end
class Net::HTTPBadResponse < StandardError
end
class Net::HTTPHeaderSyntaxError < StandardError
end
class Net::HTTP < Net::Protocol
end
