# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/oauth2/all/oauth2.rbi
#
# oauth2-2.0.12

module OAuth2
end
module OAuth2::Version
  extend VersionGem::Api
  extend VersionGem::Basic
end
module OAuth2::FilteredAttributes
end
module OAuth2::FilteredAttributes::ClassMethods
end
class OAuth2::Error < StandardError
end
class OAuth2::Authenticator
  extend OAuth2::FilteredAttributes::ClassMethods
  include OAuth2::FilteredAttributes
end
class OAuth2::ConnectionError < Faraday::ConnectionFailed
end
class OAuth2::TimeoutError < Faraday::TimeoutError
end
class OAuth2::Client
  extend OAuth2::FilteredAttributes::ClassMethods
  include OAuth2::FilteredAttributes
end
module OAuth2::Strategy
end
class OAuth2::Strategy::Base
end
class OAuth2::Strategy::AuthCode < OAuth2::Strategy::Base
end
class OAuth2::Strategy::Implicit < OAuth2::Strategy::Base
end
class OAuth2::Strategy::Password < OAuth2::Strategy::Base
end
class OAuth2::Strategy::ClientCredentials < OAuth2::Strategy::Base
end
class OAuth2::Strategy::Assertion < OAuth2::Strategy::Base
end
class OAuth2::AccessToken
  extend OAuth2::FilteredAttributes::ClassMethods
  include OAuth2::FilteredAttributes
end
class OAuth2::Response
end
