# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/omniauth/all/omniauth.rbi
#
# omniauth-2.1.3

module OmniAuth
end
class OmniAuth::Error < StandardError
end
module OmniAuth::Strategies
end
class OmniAuth::Configuration
  extend Singleton::SingletonClassMethods
  include Singleton
end
module OmniAuth::Utils
end
class OmniAuth::KeyStore < Hashie::Mash
end
class OmniAuth::NoSessionError < StandardError
end
module OmniAuth::Strategy
end
module OmniAuth::Strategy::ClassMethods
end
class OmniAuth::Strategy::Options < OmniAuth::KeyStore
end
class OmniAuth::FailureEndpoint
end
class OmniAuth::AuthenticityError < StandardError
end
class OmniAuth::AuthenticityTokenProtection < Rack::Protection::AuthenticityToken
end
class OmniAuth::Form
end
class OmniAuth::AuthHash < OmniAuth::KeyStore
end
class OmniAuth::AuthHash::InfoHash < OmniAuth::KeyStore
end
class OmniAuth::Builder < Rack::Builder
end
