# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/prettier_print/all/prettier_print.rbi
#
# prettier_print-1.2.1

class PrettierPrint
end
class PrettierPrint::SingleLine
end
class PrettierPrint::SingleLine::IfBreakBuilder
end
class PrettierPrint::Align
end
class PrettierPrint::Breakable
end
class PrettierPrint::BreakParent
end
class PrettierPrint::Group
end
class PrettierPrint::IfBreak
end
class PrettierPrint::Indent
end
class PrettierPrint::LineSuffix
end
class PrettierPrint::Text
end
class PrettierPrint::Trim
end
module PrettierPrint::Buffer
end
class PrettierPrint::Buffer::StringBuffer
end
class PrettierPrint::Buffer::ArrayBuffer
end
class PrettierPrint::IfBreakBuilder
end
class PrettierPrint::IfFlatIgnore
end
