# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/prettyprint/all/prettyprint.rbi
#
# prettyprint-0.2.0

class PrettyPrint
  def break_outmost_groups; end
  def breakable(sep = nil, width = nil); end
  def current_group; end
  def fill_breakable(sep = nil, width = nil); end
  def flush; end
  def genspace; end
  def group(indent = nil, open_obj = nil, close_obj = nil, open_width = nil, close_width = nil); end
  def group_queue; end
  def group_sub; end
  def indent; end
  def initialize(output = nil, maxwidth = nil, newline = nil, &genspace); end
  def maxwidth; end
  def nest(indent); end
  def newline; end
  def output; end
  def self.format(output = nil, maxwidth = nil, newline = nil, genspace = nil); end
  def self.singleline_format(output = nil, maxwidth = nil, newline = nil, genspace = nil); end
  def text(obj, width = nil); end
end
class PrettyPrint::Text
  def add(obj, width); end
  def initialize; end
  def output(out, output_width); end
  def width; end
end
class PrettyPrint::Breakable
  def indent; end
  def initialize(sep, width, q); end
  def obj; end
  def output(out, output_width); end
  def width; end
end
class PrettyPrint::Group
  def break; end
  def break?; end
  def breakables; end
  def depth; end
  def first?; end
  def initialize(depth); end
end
class PrettyPrint::GroupQueue
  def delete(group); end
  def deq; end
  def enq(group); end
  def initialize(*groups); end
end
class PrettyPrint::SingleLine
  def breakable(sep = nil, width = nil); end
  def first?; end
  def flush; end
  def group(indent = nil, open_obj = nil, close_obj = nil, open_width = nil, close_width = nil); end
  def initialize(output, maxwidth = nil, newline = nil); end
  def nest(indent); end
  def text(obj, width = nil); end
end
