# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-protection/all/rack-protection.rbi
#
# rack-protection-4.1.1

module Rack
end
module Rack::Protection
end
class Rack::Protection::Base
end
class Rack::Protection::AuthenticityToken < Rack::Protection::Base
end
