# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/redis/all/redis.rbi
#
# redis-5.4.1

class Redis
  include Redis::Commands
end
class Redis::BaseError < StandardError
end
class Redis::ProtocolError < Redis::BaseError
end
class Redis::CommandError < Redis::BaseError
end
class Redis::PermissionError < Redis::CommandError
end
class Redis::WrongTypeError < Redis::CommandError
end
class Redis::OutOfMemoryError < Redis::CommandError
end
class Redis::NoScriptError < Redis::CommandError
end
class Redis::BaseConnectionError < Redis::BaseError
end
class Redis::CannotConnectError < Redis::BaseConnectionError
end
class Redis::ConnectionError < Redis::BaseConnectionError
end
class Redis::TimeoutError < Redis::BaseConnectionError
end
class Redis::InheritedError < Redis::BaseConnectionError
end
class Redis::ReadOnlyError < Redis::BaseConnectionError
end
class Redis::InvalidClientOptionError < Redis::BaseError
end
class Redis::SubscriptionError < Redis::BaseError
end
module Redis::Commands
  include Redis::Commands::Bitmaps
  include Redis::Commands::Cluster
  include Redis::Commands::Connection
  include Redis::Commands::Geo
  include Redis::Commands::Hashes
  include Redis::Commands::HyperLogLog
  include Redis::Commands::Keys
  include Redis::Commands::Lists
  include Redis::Commands::Pubsub
  include Redis::Commands::Scripting
  include Redis::Commands::Server
  include Redis::Commands::Sets
  include Redis::Commands::SortedSets
  include Redis::Commands::Streams
  include Redis::Commands::Strings
  include Redis::Commands::Transactions
end
module Redis::Commands::Bitmaps
end
module Redis::Commands::Cluster
end
module Redis::Commands::Connection
end
module Redis::Commands::Geo
end
module Redis::Commands::Hashes
end
module Redis::Commands::HyperLogLog
end
module Redis::Commands::Keys
end
module Redis::Commands::Lists
end
module Redis::Commands::Pubsub
end
module Redis::Commands::Scripting
end
module Redis::Commands::Server
end
module Redis::Commands::Sets
end
module Redis::Commands::SortedSets
end
module Redis::Commands::Streams
end
module Redis::Commands::Strings
end
module Redis::Commands::Transactions
end
class Redis::Client < RedisClient
end
class Redis::PipelinedConnection
  include Redis::Commands
end
class Redis::MultiConnection < Redis::PipelinedConnection
end
class Redis::FutureNotReady < RuntimeError
end
class Redis::Future < BasicObject
end
class Redis::MultiFuture < Redis::Future
end
class Redis::SubscribedClient
end
class Redis::Subscription
end
class Redis::Deprecated < StandardError
end
module Redis::Connection
end
