# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/redis-client/all/redis-client.rbi
#
# redis-client-0.25.1

class RedisClient
  include RedisClient::Common
end
module RedisClient::CommandBuilder
  extend RedisClient::CommandBuilder
end
class RedisClient::URLConfig
end
class RedisClient::Config
  include RedisClient::Config::Common
end
module RedisClient::Config::Common
end
module RedisClient::PIDCache
end
module RedisClient::PIDCache::CoreExt
end
class RedisClient::SentinelConfig
  include RedisClient::Config::Common
end
class RedisClient::BasicMiddleware
end
class RedisClient::Middlewares < RedisClient::BasicMiddleware
end
class RedisClient::Pooled
  include RedisClient::Common
end
class RedisClient::CircuitBreaker
end
module RedisClient::CircuitBreaker::Middleware
end
class RedisClient::CircuitBreaker::OpenCircuitError < RedisClient::CannotConnectError
end
module RedisClient::ConnectionMixin
end
class RedisClient::RubyConnection
  include RedisClient::ConnectionMixin
end
class RedisClient::RubyConnection::BufferedIO
end
module RedisClient::RESP3
end
class RedisClient::RESP3::Error < RedisClient::Error
end
class RedisClient::RESP3::UnknownType < RedisClient::RESP3::Error
end
class RedisClient::RESP3::SyntaxError < RedisClient::RESP3::Error
end
module RedisClient::Common
end
module RedisClient::HasConfig
end
class RedisClient::Error < StandardError
  include RedisClient::HasConfig
end
class RedisClient::ProtocolError < RedisClient::Error
end
class RedisClient::UnsupportedServer < RedisClient::Error
end
class RedisClient::ConnectionError < RedisClient::Error
end
class RedisClient::CannotConnectError < RedisClient::ConnectionError
end
class RedisClient::FailoverError < RedisClient::ConnectionError
end
class RedisClient::TimeoutError < RedisClient::ConnectionError
end
class RedisClient::ReadTimeoutError < RedisClient::TimeoutError
end
class RedisClient::WriteTimeoutError < RedisClient::TimeoutError
end
class RedisClient::CheckoutTimeoutError < RedisClient::TimeoutError
end
module RedisClient::HasCommand
end
module RedisClient::HasCode
end
class RedisClient::CommandError < RedisClient::Error
  include RedisClient::HasCode
  include RedisClient::HasCommand
end
class RedisClient::AuthenticationError < RedisClient::CommandError
end
class RedisClient::PermissionError < RedisClient::CommandError
end
class RedisClient::WrongTypeError < RedisClient::CommandError
end
class RedisClient::OutOfMemoryError < RedisClient::CommandError
end
class RedisClient::NoScriptError < RedisClient::CommandError
end
class RedisClient::ReadOnlyError < RedisClient::ConnectionError
  include RedisClient::HasCode
  include RedisClient::HasCommand
end
class RedisClient::MasterDownError < RedisClient::ConnectionError
  include RedisClient::HasCode
  include RedisClient::HasCommand
end
class RedisClient::PubSub
end
class RedisClient::Multi
end
class RedisClient::Pipeline < RedisClient::Multi
end
