# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rqrcode/all/rqrcode.rbi
#
# rqrcode-3.1.0

module RQRCode
end
class RQRCode::QRCode
  extend Forwardable
  include RQRCode::Export::ANSI
  include RQRCode::Export::HTML
  include RQRCode::Export::PNG
  include RQRCode::Export::SVG
end
module RQRCode::Export
end
module RQRCode::Export::ANSI
end
module RQRCode::Export::HTML
end
class RQRCode::Export::HTML::Rows < Anonymous_Struct_60
end
class RQRCode::Export::HTML::Row < Anonymous_Struct_61
end
class RQRCode::Export::HTML::Cell < Anonymous_Struct_62
end
module RQRCode::Export::PNG
end
module RQRCode::Export::SVG
end
class RQRCode::Export::SVG::BaseOutputSVG
end
class RQRCode::Export::SVG::Path < RQRCode::Export::SVG::BaseOutputSVG
end
class RQRCode::Export::SVG::Rect < RQRCode::Export::SVG::BaseOutputSVG
end
class RQRCode::Export::SVG::Edge < Anonymous_Struct_63
end
