# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rqrcode_core/all/rqrcode_core.rbi
#
# rqrcode_core-2.0.0

module RQRCodeCore
end
class RQRCodeCore::QR8bitByte
end
class RQRCodeCore::QRAlphanumeric
end
class RQRCodeCore::QRBitBuffer
end
class RQRCodeCore::QRCodeArgumentError < ArgumentError
end
class RQRCodeCore::QRCodeRunTimeError < RuntimeError
end
class RQRCodeCore::QRCode
  extend Gem::Deprecate
end
class RQRCodeCore::QRMath
end
class RQRCodeCore::QRMulti
end
class RQRCodeCore::QRNumeric
end
class RQRCodeCore::QRPolynomial
end
class RQRCodeCore::QRRSBlock
end
class RQRCodeCore::QRSegment
end
class RQRCodeCore::QRUtil
end
