# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rspec-rails/all/rspec-rails.rbi
#
# rspec-rails-8.0.1

module RSpec
end
module RSpec::Rails
end
module RSpec::Rails::FeatureCheck
end
class RSpec::Rails::Railtie < Rails::Railtie
end
