# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/securerandom/all/securerandom.rbi
#
# securerandom-0.4.1

module SecureRandom
  def self.bytes(n); end
  def self.gen_random(n); end
  def self.gen_random_openssl(n); end
  def self.gen_random_urandom(n); end
  extend Random::Formatter
end
