# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/snaky_hash/all/snaky_hash.rbi
#
# snaky_hash-2.0.3

module SnakyHash
end
module SnakyHash::Version
  extend VersionGem::Api
  extend VersionGem::Basic
end
class SnakyHash::Extensions
end
module SnakyHash::Serializer
end
module SnakyHash::Serializer::Modulizer
end
module SnakyHash::Serializer::BackportedInstanceMethods
end
module SnakyHash::Serializer::ConvenienceInstanceMethods
end
class SnakyHash::Snake < Module
end
module SnakyHash::Snake::SnakyModulizer
end
class SnakyHash::StringKeyed < Hashie::Mash
  include Anonymous_Module_55
  include Anonymous_SnakyHash_Snake_56
end
module Anonymous_SnakyHash_Snake_56
end
module Anonymous_Module_55
end
class SnakyHash::SymbolKeyed < Hashie::Mash
  include Anonymous_Module_57
  include Anonymous_SnakyHash_Snake_58
end
module Anonymous_SnakyHash_Snake_58
end
module Anonymous_Module_57
end
class SnakyHash::Error < StandardError
end
