# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/syntax_tree/all/syntax_tree.rbi
#
# syntax_tree-6.3.0

module SyntaxTree
end
class SyntaxTree::Location
end
class SyntaxTree::Node
end
module SyntaxTree::ArrayMatch
end
class SyntaxTree::BEGINBlock < SyntaxTree::Node
end
class SyntaxTree::CHAR < SyntaxTree::Node
end
class SyntaxTree::ENDBlock < SyntaxTree::Node
end
class SyntaxTree::EndContent < SyntaxTree::Node
end
class SyntaxTree::AliasNode < SyntaxTree::Node
end
class SyntaxTree::AliasNode::AliasArgumentFormatter
end
class SyntaxTree::ARef < SyntaxTree::Node
end
class SyntaxTree::ARefField < SyntaxTree::Node
end
class SyntaxTree::ArgParen < SyntaxTree::Node
end
class SyntaxTree::Args < SyntaxTree::Node
end
class SyntaxTree::ArgBlock < SyntaxTree::Node
end
class SyntaxTree::ArgStar < SyntaxTree::Node
end
class SyntaxTree::ArgsForward < SyntaxTree::Node
end
class SyntaxTree::ArrayLiteral < SyntaxTree::Node
end
class SyntaxTree::ArrayLiteral::BreakableSpaceSeparator
end
class SyntaxTree::ArrayLiteral::QWordsFormatter
end
class SyntaxTree::ArrayLiteral::QSymbolsFormatter
end
class SyntaxTree::ArrayLiteral::EmptyWithCommentsFormatter
end
class SyntaxTree::AryPtn < SyntaxTree::Node
end
class SyntaxTree::AryPtn::RestFormatter
end
module SyntaxTree::AssignFormatting
end
class SyntaxTree::Assign < SyntaxTree::Node
end
class SyntaxTree::Assoc < SyntaxTree::Node
end
class SyntaxTree::AssocSplat < SyntaxTree::Node
end
class SyntaxTree::Backref < SyntaxTree::Node
end
class SyntaxTree::Backtick < SyntaxTree::Node
end
module SyntaxTree::HashKeyFormatter
end
class SyntaxTree::HashKeyFormatter::Labels
end
class SyntaxTree::HashKeyFormatter::Rockets
end
class SyntaxTree::HashKeyFormatter::Identity
end
class SyntaxTree::BareAssocHash < SyntaxTree::Node
end
class SyntaxTree::Begin < SyntaxTree::Node
end
class SyntaxTree::PinnedBegin < SyntaxTree::Node
end
class SyntaxTree::Binary < SyntaxTree::Node
end
class SyntaxTree::BlockVar < SyntaxTree::Node
end
class SyntaxTree::BlockVar::Separator
end
class SyntaxTree::BlockArg < SyntaxTree::Node
end
class SyntaxTree::BodyStmt < SyntaxTree::Node
end
class SyntaxTree::FlowControlFormatter
end
class SyntaxTree::Break < SyntaxTree::Node
end
class SyntaxTree::CallOperatorFormatter
end
class SyntaxTree::CallChainFormatter
end
class SyntaxTree::CallNode < SyntaxTree::Node
end
class SyntaxTree::Case < SyntaxTree::Node
end
class SyntaxTree::RAssign < SyntaxTree::Node
end
class SyntaxTree::ClassDeclaration < SyntaxTree::Node
end
class SyntaxTree::Comma < SyntaxTree::Node
end
class SyntaxTree::Command < SyntaxTree::Node
end
class SyntaxTree::CommandCall < SyntaxTree::Node
end
class SyntaxTree::Comment < SyntaxTree::Node
end
class SyntaxTree::Const < SyntaxTree::Node
end
class SyntaxTree::ConstPathField < SyntaxTree::Node
end
class SyntaxTree::ConstPathRef < SyntaxTree::Node
end
class SyntaxTree::ConstRef < SyntaxTree::Node
end
class SyntaxTree::CVar < SyntaxTree::Node
end
class SyntaxTree::DefNode < SyntaxTree::Node
end
class SyntaxTree::Defined < SyntaxTree::Node
end
class SyntaxTree::BlockNode < SyntaxTree::Node
end
class SyntaxTree::BlockNode::BlockOpenFormatter
end
class SyntaxTree::RangeNode < SyntaxTree::Node
end
module SyntaxTree::Quotes
end
class SyntaxTree::DynaSymbol < SyntaxTree::Node
end
class SyntaxTree::Else < SyntaxTree::Node
end
class SyntaxTree::Elsif < SyntaxTree::Node
end
class SyntaxTree::EmbDoc < SyntaxTree::Node
end
class SyntaxTree::EmbExprBeg < SyntaxTree::Node
end
class SyntaxTree::EmbExprEnd < SyntaxTree::Node
end
class SyntaxTree::EmbVar < SyntaxTree::Node
end
class SyntaxTree::Ensure < SyntaxTree::Node
end
class SyntaxTree::ExcessedComma < SyntaxTree::Node
end
class SyntaxTree::Field < SyntaxTree::Node
end
class SyntaxTree::FloatLiteral < SyntaxTree::Node
end
class SyntaxTree::FndPtn < SyntaxTree::Node
end
class SyntaxTree::For < SyntaxTree::Node
end
class SyntaxTree::GVar < SyntaxTree::Node
end
class SyntaxTree::HashLiteral < SyntaxTree::Node
end
class SyntaxTree::HashLiteral::EmptyWithCommentsFormatter
end
class SyntaxTree::Heredoc < SyntaxTree::Node
end
class SyntaxTree::HeredocBeg < SyntaxTree::Node
end
class SyntaxTree::HeredocEnd < SyntaxTree::Node
end
class SyntaxTree::HshPtn < SyntaxTree::Node
end
class SyntaxTree::HshPtn::KeywordFormatter
end
class SyntaxTree::HshPtn::KeywordRestFormatter
end
class SyntaxTree::Ident < SyntaxTree::Node
end
module SyntaxTree::ContainsAssignment
end
module SyntaxTree::Ternaryable
end
class SyntaxTree::ConditionalFormatter
end
class SyntaxTree::IfNode < SyntaxTree::Node
end
class SyntaxTree::IfOp < SyntaxTree::Node
end
class SyntaxTree::Imaginary < SyntaxTree::Node
end
class SyntaxTree::In < SyntaxTree::Node
end
class SyntaxTree::Int < SyntaxTree::Node
end
class SyntaxTree::IVar < SyntaxTree::Node
end
class SyntaxTree::Kw < SyntaxTree::Node
end
class SyntaxTree::KwRestParam < SyntaxTree::Node
end
class SyntaxTree::Label < SyntaxTree::Node
end
class SyntaxTree::LabelEnd < SyntaxTree::Node
end
class SyntaxTree::Lambda < SyntaxTree::Node
end
class SyntaxTree::LambdaVar < SyntaxTree::Node
end
class SyntaxTree::LBrace < SyntaxTree::Node
end
class SyntaxTree::LBracket < SyntaxTree::Node
end
class SyntaxTree::LParen < SyntaxTree::Node
end
class SyntaxTree::MAssign < SyntaxTree::Node
end
class SyntaxTree::MethodAddBlock < SyntaxTree::Node
end
class SyntaxTree::MLHS < SyntaxTree::Node
end
class SyntaxTree::MLHSParen < SyntaxTree::Node
end
class SyntaxTree::ModuleDeclaration < SyntaxTree::Node
end
class SyntaxTree::MRHS < SyntaxTree::Node
end
class SyntaxTree::Next < SyntaxTree::Node
end
class SyntaxTree::Op < SyntaxTree::Node
end
class SyntaxTree::OpAssign < SyntaxTree::Node
end
module SyntaxTree::Parentheses
end
class SyntaxTree::Params < SyntaxTree::Node
end
class SyntaxTree::Params::OptionalFormatter
end
class SyntaxTree::Params::KeywordFormatter
end
class SyntaxTree::Params::KeywordRestFormatter
end
class SyntaxTree::Paren < SyntaxTree::Node
end
class SyntaxTree::Period < SyntaxTree::Node
end
class SyntaxTree::Program < SyntaxTree::Node
end
class SyntaxTree::QSymbols < SyntaxTree::Node
end
class SyntaxTree::QSymbolsBeg < SyntaxTree::Node
end
class SyntaxTree::QWords < SyntaxTree::Node
end
class SyntaxTree::QWordsBeg < SyntaxTree::Node
end
class SyntaxTree::RationalLiteral < SyntaxTree::Node
end
class SyntaxTree::RBrace < SyntaxTree::Node
end
class SyntaxTree::RBracket < SyntaxTree::Node
end
class SyntaxTree::Redo < SyntaxTree::Node
end
class SyntaxTree::RegexpContent < SyntaxTree::Node
end
class SyntaxTree::RegexpBeg < SyntaxTree::Node
end
class SyntaxTree::RegexpEnd < SyntaxTree::Node
end
class SyntaxTree::RegexpLiteral < SyntaxTree::Node
end
class SyntaxTree::RescueEx < SyntaxTree::Node
end
class SyntaxTree::Rescue < SyntaxTree::Node
end
class SyntaxTree::RescueMod < SyntaxTree::Node
end
class SyntaxTree::RestParam < SyntaxTree::Node
end
class SyntaxTree::Retry < SyntaxTree::Node
end
class SyntaxTree::ReturnNode < SyntaxTree::Node
end
class SyntaxTree::RParen < SyntaxTree::Node
end
class SyntaxTree::SClass < SyntaxTree::Node
end
class SyntaxTree::Statements < SyntaxTree::Node
end
class SyntaxTree::StringContent < SyntaxTree::Node
end
class SyntaxTree::StringConcat < SyntaxTree::Node
end
class SyntaxTree::StringDVar < SyntaxTree::Node
end
class SyntaxTree::StringEmbExpr < SyntaxTree::Node
end
class SyntaxTree::StringLiteral < SyntaxTree::Node
end
class SyntaxTree::Super < SyntaxTree::Node
end
class SyntaxTree::SymBeg < SyntaxTree::Node
end
class SyntaxTree::SymbolContent < SyntaxTree::Node
end
class SyntaxTree::SymbolLiteral < SyntaxTree::Node
end
class SyntaxTree::Symbols < SyntaxTree::Node
end
class SyntaxTree::SymbolsBeg < SyntaxTree::Node
end
class SyntaxTree::TLambda < SyntaxTree::Node
end
class SyntaxTree::TLamBeg < SyntaxTree::Node
end
class SyntaxTree::TopConstField < SyntaxTree::Node
end
class SyntaxTree::TopConstRef < SyntaxTree::Node
end
class SyntaxTree::TStringBeg < SyntaxTree::Node
end
class SyntaxTree::TStringContent < SyntaxTree::Node
end
class SyntaxTree::TStringEnd < SyntaxTree::Node
end
class SyntaxTree::Not < SyntaxTree::Node
end
class SyntaxTree::Unary < SyntaxTree::Node
end
class SyntaxTree::Undef < SyntaxTree::Node
end
class SyntaxTree::Undef::UndefArgumentFormatter
end
class SyntaxTree::UnlessNode < SyntaxTree::Node
end
class SyntaxTree::LoopFormatter
end
class SyntaxTree::UntilNode < SyntaxTree::Node
end
class SyntaxTree::VarField < SyntaxTree::Node
end
class SyntaxTree::VarRef < SyntaxTree::Node
end
class SyntaxTree::PinnedVarRef < SyntaxTree::Node
end
class SyntaxTree::VCall < SyntaxTree::Node
end
class SyntaxTree::VoidStmt < SyntaxTree::Node
end
class SyntaxTree::When < SyntaxTree::Node
end
class SyntaxTree::When::Separator
end
class SyntaxTree::WhileNode < SyntaxTree::Node
end
class SyntaxTree::Word < SyntaxTree::Node
end
class SyntaxTree::Words < SyntaxTree::Node
end
class SyntaxTree::WordsBeg < SyntaxTree::Node
end
class SyntaxTree::XString < SyntaxTree::Node
end
class SyntaxTree::XStringLiteral < SyntaxTree::Node
end
class SyntaxTree::YieldNode < SyntaxTree::Node
end
class SyntaxTree::ZSuper < SyntaxTree::Node
end
class SyntaxTree::BasicVisitor
end
class SyntaxTree::BasicVisitor::VisitMethodError < StandardError
end
class SyntaxTree::BasicVisitor::VisitMethodChecker
end
class SyntaxTree::BasicVisitor::VisitMethodsChecker < Module
end
class SyntaxTree::Visitor < SyntaxTree::BasicVisitor
end
class SyntaxTree::Formatter < PrettierPrint
end
class SyntaxTree::Formatter::SemanticVersion < Gem::Version
end
class SyntaxTree::Formatter::Options
end
class SyntaxTree::Parser < Ripper
end
class SyntaxTree::Parser::ParseError < StandardError
end
class SyntaxTree::Parser::SingleByteString
end
class SyntaxTree::Parser::MultiByteString
end
class SyntaxTree::Parser::TokenList
end
class SyntaxTree::Parser::PinVisitor < SyntaxTree::Visitor
  extend Anonymous_SyntaxTree_BasicVisitor_VisitMethodsChecker_54
end
module Anonymous_SyntaxTree_BasicVisitor_VisitMethodsChecker_54
end
class SyntaxTree::Parser::Semicolon
end
