# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/turbo-rails/all/turbo-rails.rbi
#
# turbo-rails-2.0.16

module Turbo
  def current_request_id; end
  def current_request_id=(obj); end
  def draw_routes; end
  def draw_routes=(val); end
  def self.current_request_id; end
  def self.current_request_id=(obj); end
  def self.draw_routes; end
  def self.draw_routes=(val); end
  def self.railtie_helpers_paths; end
  def self.railtie_namespace; end
  def self.railtie_routes_url_helpers(include_path_helpers = nil); end
  def self.signed_stream_verifier; end
  def self.signed_stream_verifier_key; end
  def self.signed_stream_verifier_key=(arg0); end
  def self.table_name_prefix; end
  def self.use_relative_model_naming?; end
  def self.with_request_id(request_id); end
  extend ActiveSupport::Autoload
end
class Turbo::Engine < Rails::Engine
end
module Turbo::Streams::TurboStreamsTagBuilder
end
module Turbo::Frames::FrameRequest
  extend ActiveSupport::Concern
end
module Turbo::Native::Navigation
  extend ActiveSupport::Concern
end
module Turbo::DriveHelper
end
module Turbo::FramesHelper
end
module Turbo::IncludesHelper
end
module Turbo::StreamsHelper
end
module Turbo::Streams::ActionHelper
  include ActionView::Helpers::TagHelper
end
module Turbo::RequestIdTracking
  extend ActiveSupport::Concern
end
module Turbo::Broadcastable
  extend ActiveSupport::Concern
end
module Turbo::Broadcastable::ClassMethods
end
module Turbo::Streams::Broadcasts
  include Turbo::Streams::ActionHelper
end
module Turbo::Streams::StreamName
end
module Turbo::Streams::StreamName::ClassMethods
end
class Turbo::StreamsChannel < ActionCable::Channel::Base
  extend Turbo::Streams::Broadcasts
  include Turbo::Streams::StreamName::ClassMethods
end
module Anonymous_Module_46
  extend ActiveSupport::Concern
  extend Anonymous_Module_47
  extend Anonymous_Module_48
  include ActionDispatch::Routing::UrlFor
  include Anonymous_Module_47
  include Anonymous_Module_48
end
class Turbo::Native::NavigationController < ActionController::Base
  include ActionDispatch::Routing::UrlFor
  include Anonymous_Module_46
end
class Turbo::Debouncer
end
class Turbo::ThreadDebouncer
end
class Turbo::Streams::TagBuilder
  include Turbo::Streams::ActionHelper
end
class Turbo::Streams::ActionBroadcastJob < ActiveJob::Base
end
class Turbo::Streams::BroadcastJob < ActiveJob::Base
end
class Turbo::Streams::BroadcastStreamJob < ActiveJob::Base
end
module Turbo::TestAssertions
  extend ActiveSupport::Concern
end
module Turbo::Broadcastable::TestHelper
  extend ActiveSupport::Concern
end
