# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/version_gem/all/version_gem.rbi
#
# version_gem-1.1.8

module VersionGem
end
module VersionGem::Version
  extend VersionGem::Api
  extend VersionGem::Basic
end
class VersionGem::Error < RuntimeError
end
module VersionGem::Api
end
module VersionGem::Basic
end
module VersionGem::Epoch
end
module VersionGem::Epoch::OverloadApiForEpoch
end
