---
- name: Install Ruby dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev

- name: Download and install Ruby
  become: yes
  become_user: deploy
  args:
    chdir: "/home/{{ app_user }}"
  shell: |
    wget "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-{{ ruby_version }}.tar.gz"
    tar -xzvf ruby-{{ ruby_version }}.tar.gz
    cd ruby-{{ ruby_version }} && ./configure && make && make install
  args:
    creates: /usr/local/bin/ruby

- name: Verify Ruby installation
  command: ruby --version
