
plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3.4
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'lib/**/*.rb'
    - 'rubocop_output.txt'
    - 'rubocop_remaining.txt'
    - 'final_rubocop.txt'
    - 'rubocop_results.json'
    - 'check_rubocop.sh'
    - 'app/helpers/network_interface_helper_*'
    - 'app/views/**/*.erb'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

# Allow longer methods in some cases
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/**/*'
    - 'spec/**/*'

# Allow higher ABC size in some cases
Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'db/migrate/**/*'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/admin_controller.rb'

# Allow larger blocks in specs and configuration
Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

# Disable some Rails cops that might be too strict
Rails/I18nLocaleTexts:
  Enabled: false

# Allow trailing whitespace to be auto-corrected
Layout/TrailingWhitespace:
  AutoCorrect: true

# Allow some flexibility in line length for specific files
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/environments/**/*'
    - 'spec/**/*'

# RSpec Configuration - Disable overly strict cops
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/LetSetup:
  Enabled: false