---
- name: Install Caddy
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - debian-keyring
    - debian-archive-keyring
    - apt-transport-https

- name: Add Caddy GPG key and repository
  shell: |
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | tee /etc/apt/trusted.gpg.d/caddy-stable.asc
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
  args:
    creates: /etc/apt/trusted.gpg.d/caddy-stable.asc

- name: Install Caddy package
  apt:
    name: caddy
    update_cache: yes
    state: present

- name: Create Caddyfile
  copy:
    dest: /etc/caddy/Caddyfile
    content: |
      {{ lookup('ansible.builtin.env', 'DOMAIN_NAME') }} {
        root * {{ app_directory }}/public
        encode gzip
        file_server
        reverse_proxy / http://localhost:3000 {
          header_up X-Real-IP {remote}
          header_up X-Forwarded-For {remote}
          header_up X-Forwarded-Proto {scheme}
        }
      }

- name: Reload Caddy
  systemd:
    name: caddy
    state: reloaded
