name: "gate_wireguard"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
    - redis
    - mysql

  redis:
    image: redis:7.2
    restart: unless-stopped
    volumes:
    - redis-data:/data

  mysql:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        MYSQL_ROOT_HOST: "%"
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
    - default

volumes:
  redis-data:
  mysql-data:
