---
- name: Deploy Caddy reverse proxy for Gate-WireGuard
  hosts: all
  become: yes
  vars:
    # deploy_user and domain are passed via --extra-vars
    home_path: "/home/{{ deploy_user }}"
    app_path: "{{ home_path }}/gate-wireguard"

  tasks:
    # ----------------------------------------------------------------
    # 1. Install Caddy (from official apt repo)
    # ----------------------------------------------------------------
    - name: Install prerequisites for Caddy repo
      ansible.builtin.apt:
        name:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
          - curl
        state: present
        update_cache: yes

    - name: Add Caddy GPG key
      ansible.builtin.shell: |
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

    - name: Add Caddy apt repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/caddy-stable.list
        content: "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main\n"
        mode: "0644"

    - name: Install Caddy
      ansible.builtin.apt:
        name: caddy
        state: present
        update_cache: yes

    # ----------------------------------------------------------------
    # 2. Detect Puma port from deployed config
    # ----------------------------------------------------------------
    - name: Detect Puma port from config
      ansible.builtin.shell: grep '^[[:space:]]*port ' {{ app_path }}/config/puma.rb | grep -oP '\{\s*\K[0-9]+'
      register: detected_port
      changed_when: false

    - name: Set puma_port fact
      ansible.builtin.set_fact:
        puma_port: "{{ detected_port.stdout }}"

    - name: Verify Puma port was detected
      ansible.builtin.fail:
        msg: "Could not detect Puma port from {{ app_path }}/config/puma.rb"
      when: puma_port == ""

    # ----------------------------------------------------------------
    # 3. Configure logging directory
    # ----------------------------------------------------------------
    - name: Create Caddy log directory
      ansible.builtin.file:
        path: /var/log/caddy
        state: directory
        owner: caddy
        group: caddy
        mode: "0755"

    # ----------------------------------------------------------------
    # 4. Configure Caddy conf.d structure
    # ----------------------------------------------------------------
    - name: Create Caddy conf.d directory
      ansible.builtin.file:
        path: /etc/caddy/conf.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Deploy main Caddyfile with global log and conf.d import
      ansible.builtin.copy:
        dest: /etc/caddy/Caddyfile
        content: |
          {
              log {
                  output file /var/log/caddy/caddy.log {
                      roll_size 100MiB
                      roll_keep 5
                      roll_keep_for 720h
                  }
                  level INFO
              }
          }

          import /etc/caddy/conf.d/*.caddy
        owner: root
        group: root
        mode: "0644"
      notify: Reload Caddy

    # ----------------------------------------------------------------
    # 5. Deploy site-specific Caddy config
    # ----------------------------------------------------------------
    - name: Deploy Caddy site config for {{ domain }}
      ansible.builtin.copy:
        dest: "/etc/caddy/conf.d/{{ domain }}.caddy"
        content: |
          {{ domain }} {
              reverse_proxy localhost:{{ puma_port }}

              log {
                  output file /var/log/caddy/{{ domain }}.access.log {
                      roll_size 100MiB
                      roll_keep 5
                      roll_keep_for 720h
                  }
                  format json
                  level DEBUG
              }
          }
        owner: root
        group: root
        mode: "0644"
      notify: Reload Caddy

    # ----------------------------------------------------------------
    # 6. Deploy logrotate config for Caddy
    # ----------------------------------------------------------------
    - name: Deploy logrotate config for Caddy
      ansible.builtin.copy:
        dest: /etc/logrotate.d/caddy
        content: |
          /var/log/caddy/*.log {
              daily
              missingok
              rotate 14
              compress
              delaycompress
              notifempty
              create 0644 caddy caddy
              sharedscripts
              postrotate
                  systemctl reload caddy > /dev/null 2>&1 || true
              endscript
          }
        owner: root
        group: root
        mode: "0644"

    # ----------------------------------------------------------------
    # 7. Allow HTTP (port 80) in UFW for ACME challenge
    # ----------------------------------------------------------------
    - name: Allow HTTP (port 80) for Let's Encrypt ACME challenge
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp

    # ----------------------------------------------------------------
    # 8. Enable and start Caddy
    # ----------------------------------------------------------------
    - name: Enable and start Caddy
      ansible.builtin.systemd:
        name: caddy
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: Reload Caddy
      ansible.builtin.systemd:
        name: caddy
        state: reloaded
