---
- name: Install packages and gems on localhost
  hosts: localhost
  become: yes # Use sudo to become the root user

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install necessary packages
      ansible.builtin.apt:
        name:
          - libmysqlclient-dev
          - mysql-client
          - ruby-full
          - nodejs
          - npm
          - libyaml-dev
          - build-essential
          - default-libmysqlclient-dev
          - libvips
          - pkg-config
          - inotify-tools
          - openssh-server
          - wireguard
          - net-tools
          - watchman
        state: present

    - name: Install Rails gem
      ansible.builtin.gem:
        name: rails
        state: present
        user_install: no # Install the gem system-wide

    - name: Install Bundler gem
      ansible.builtin.gem:
        name: bundler
        state: present
        user_install: no # Install the gem system-wide
