---
- name: Install basic system packages
  apt:
    name:
      - git
      - curl
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev
      - nodejs
      - yarn
      - libmysqlclient-dev
      - mysql-client
      - ruby-full
      - libyaml-dev
      - build-essential
      - default-libmysqlclient-dev
      - libvips
      - pkg-config
      - mysql-server
      - inotify-tools
      - openssh-server
      - wireguard
      - net-tools
    state: present
    update_cache: yes
