---
- name: Create Puma configuration file
  copy:
    dest: "{{ app_directory }}/config/puma.rb"
    content: |
      workers ENV.fetch("WEB_CONCURRENCY") { 2 }
      threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
      threads threads_count, threads_count
      preload_app!
      port ENV.fetch("PORT") { 3000 }
      environment ENV.fetch("RAILS_ENV") { "production" }
      on_worker_boot do
        ActiveRecord::Base.establish_connection if defined?(ActiveRecord)
      end

- name: Create systemd service for Puma
  copy:
    dest: /etc/systemd/system/puma.service
    content: |
      [Unit]
      Description=Puma HTTP Server
      After=network.target

      [Service]
      Type=simple
      User={{ app_user }}
      WorkingDirectory={{ app_directory }}
      ExecStart=/usr/local/bin/puma -C {{ app_directory }}/config/puma.rb
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Enable and start Puma
  systemd:
    name: puma
    enabled: yes
    state: started
